// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_superhuman = "CgkIqe6wvP0aEAIQBg"; // <GPGSID>
        public const string achievement_the_pioneer = "CgkIqe6wvP0aEAIQAw"; // <GPGSID>
        public const string achievement_photogenic_discordant = "CgkIqe6wvP0aEAIQFw"; // <GPGSID>
        public const string achievement_destrudo = "CgkIqe6wvP0aEAIQFA"; // <GPGSID>
        public const string achievement_to_the_glory_of_the_great_tetraktis = "CgkIqe6wvP0aEAIQGA"; // <GPGSID>
        public const string achievement_long_live_the_king = "CgkIqe6wvP0aEAIQDA"; // <GPGSID>
        public const string achievement_fly_on_the_wall = "CgkIqe6wvP0aEAIQEw"; // <GPGSID>
        public const string achievement_mindblowing_advertising_overseer = "CgkIqe6wvP0aEAIQHQ"; // <GPGSID>
        public const string achievement_beginner_advertising_overseer = "CgkIqe6wvP0aEAIQGQ"; // <GPGSID>
        public const string leaderboard_greedy_leaderboard = "CgkIqe6wvP0aEAIQAQ"; // <GPGSID>
        public const string achievement_intermediate_advertising_overseer = "CgkIqe6wvP0aEAIQGg"; // <GPGSID>
        public const string leaderboard_meditative_leaderboard = "CgkIqe6wvP0aEAIQAg"; // <GPGSID>
        public const string achievement_street_magician = "CgkIqe6wvP0aEAIQFg"; // <GPGSID>
        public const string achievement_trickster = "CgkIqe6wvP0aEAIQBw"; // <GPGSID>
        public const string achievement_climber = "CgkIqe6wvP0aEAIQCQ"; // <GPGSID>
        public const string achievement_so_with_what_shall_i_scrap_this = "CgkIqe6wvP0aEAIQCw"; // <GPGSID>
        public const string achievement_it_was_so_lovely = "CgkIqe6wvP0aEAIQCg"; // <GPGSID>
        public const string achievement_super_advanced_advertising_overseer = "CgkIqe6wvP0aEAIQHA"; // <GPGSID>
        public const string achievement_fly_baron = "CgkIqe6wvP0aEAIQEg"; // <GPGSID>
        public const string achievement_advanced_advertising_overseer = "CgkIqe6wvP0aEAIQGw"; // <GPGSID>
        public const string achievement_good_pupil = "CgkIqe6wvP0aEAIQCA"; // <GPGSID>
        public const string achievement_a_bit_not_enough = "CgkIqe6wvP0aEAIQDw"; // <GPGSID>
        public const string achievement_my_little_narcissist = "CgkIqe6wvP0aEAIQDQ"; // <GPGSID>
        public const string achievement_a_pretty_good_too = "CgkIqe6wvP0aEAIQEA"; // <GPGSID>
        public const string achievement_look_at_me_im_doin_something = "CgkIqe6wvP0aEAIQDg"; // <GPGSID>
        public const string leaderboard_fighter_of_evil_leaderboard = "CgkIqe6wvP0aEAIQEQ"; // <GPGSID>
        public const string achievement_lord_of_the_flies = "CgkIqe6wvP0aEAIQBA"; // <GPGSID>
        public const string achievement_mr_apathy = "CgkIqe6wvP0aEAIQFQ"; // <GPGSID>
        public const string achievement_fly_swat = "CgkIqe6wvP0aEAIQBQ"; // <GPGSID>

}

